name: "Deploy SAM Stack to Production"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: |
          for d in */ ; do
            if [ -d "${d}/nodejs" ]; then 
              cd $d/nodejs && npm install --no-package-lock --loglevel=error && cd ../.. 
            fi
          done
      - uses: r0zar/sam-deploy-action@v1.4
        env:
          TEMPLATE: "template.yaml"
          AWS_STACK_NAME: node-js-dependencies
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEV_BUCKET }}
